name: auth
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_bloc:
  dio:
  get_it:
  dartz:
  logger:
  # shared_preferences:
  go_router: ^14.6.2
  go_transitions: ^0.7.1
  flutter_dotenv: ^5.2.1
  hive_ce: ^2.8.0+2
  hive_ce_flutter: ^2.2.0
  intl: ^0.19.0
  flutter_easyloading: ^3.0.5
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.0.17
  http: ^1.3.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.14
  hive_ce_generator: 
  # dart pub run build_runner build --delete-conflicting-outputs
  flutter_lints: ^3.0.0

flutter:

  generate: true

  assets:
    # Add assets from the images directory to the application.
    - .env
    - assets/fonts/
    - assets/svgs/
  uses-material-design: true

